In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
!pip install scipy

In [ ]:
import json
import re
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
import nltk
from nltk.corpus import stopwords
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
tag_dict={
    'J':wordnet.ADJ,
    'V':wordnet.VERB,
    "N": wordnet.NOUN,
    "R": wordnet.ADV
}
def get_pos_tag(word):
    tag=nltk.pos_tag([word])[0][1][0].upper()
    return tag_dict.get(tag,wordnet.NOUN)

def clean_text(text):
    ## Remove puncuation
    #text = text.translate(string.punctuation)
    
    ## Convert words to lower case and split them
    text = text.lower().split()
    
    ## Remove stop words
    stops = set(stopwords.words("english"))
    text = [w for w in text if not w in stops and len(w) >= 3]
    
    text = " ".join(text)

    ## Clean the text
    text = re.sub(r"[^a-z0-9']", " ", text)
    text = re.sub(r"what's", "what is ", text)
    text = re.sub(r"\'s", " 's ", text)
    text = re.sub(r"\'ve", " have ", text)
    text = re.sub(r"n't", " not ", text)
    text = re.sub(r"i'm", "i am ", text)
    text = re.sub(r"\'re", " are ", text)
    text = re.sub(r"\'d", " would ", text)
    text = re.sub(r"\'ll", " will ", text)
    text = re.sub(r"0"," zero ", text)
    text = re.sub(r"1"," one ", text)
    text = re.sub(r"2"," two ", text)
    text = re.sub(r"3"," three ", text)
    text = re.sub(r"4"," four ", text)
    text = re.sub(r"5"," five ", text)
    text = re.sub(r"6"," six ", text)
    text = re.sub(r"7"," seven ", text)
    text = re.sub(r"8"," eight ", text)
    text = re.sub(r"9"," nine ", text)
    text = re.sub(r"'", " ", text)
    text = re.sub(r"\s{2,}", " ", text)
    text = re.sub(r"\n","",text)

    sentence_clean=[]
    for word in text.split():
        sentence_clean.append(lemmatizer.lemmatize(word,get_pos_tag(word)))
    return " ".join(sentence_clean)


l=[]
count=0
lemmatizer = WordNetLemmatizer() 

fg=open("drive/My Drive/AIProject/dataset_values.txt","w")
with open("drive/My Drive/AIProject/dataset.txt") as f:
    for line in f:
        if count==20000:
            break
        elif re.match("^!!!!!",line):
            try:
                s=" ".join(l)
                fin=clean_text(s)
                fg.write(fin+"\n!!!!!\n")
                count=count+1
            except:
                print("Oops!",sys.exc_info()[0],"occured.")
                pass
            l=[]
        else: 
            l.append(line)
print(count)
fg.close()

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
20000


In [ ]:
import json
import re
from watson_developer_cloud import NaturalLanguageUnderstandingV1
from watson_developer_cloud.natural_language_understanding_v1 import Features, CategoriesOptions



def pre_process(email):
    stopwords = ["a", "share", "linkthese", "about", "above", "after", "again", "against", "all", "am", "an", "and", "any","are","aren't","as","at","be","because","been","before","being","below","between","both","but","by","can't","cannot","could","couldn't","did","didn't","do","does","doesn't","doing","don't","down","during","each","few","for","from","further","had","hadn't","has","hasn't","have","haven't","having","he","he'd","he'll","he's","her","here","here's","hers","herself","him","himself","his","how","how's","i","i'd","i'll","i'm","i've","if","in","into","is","isn't","it","it's","its","itself","let's","me","more","most","mustn't","my","myself","no","nor","not","of","off","on","once","only","or","other","ought","our","ours","ourselves","out","over","own","same","shan't","she","she'd","she'll","she's","should","shouldn't","so","some","such","than","that","that's","the","their","theirs","them","themselves","then","there","there's","these","they","they'd","they'll","they're","they've","this","those","through","to","too","under","until","up","very","was","wasn't","we","we'd","we'll","we're","we've","were","weren't","what","what's","when","when's","where","where's","which","while","who","who's","whom","why","why's","with","won't","would","wouldn't","you","you'd","you'll","you're","you've","your","yours","yourself","yourselves", "this"];
    text=list(email)
    #print(text)
    for i in text:
        if i in (',','.','?','!'):
            del text[text.index(i)]
    email1="".join(text)
    text=email1.split(" ")
    final=[]
    for word in text:
        text[text.index(word)]=word.lower()
    for word in text:
        if word not in stopwords:
            final.append(word)
    return " ".join(final)

natural_language_understanding = NaturalLanguageUnderstandingV1(
    version='2018-11-16',
    iam_apikey='u8rI-gjW7N96229thht83BC2vl1SYJ0Xi1FCEih5dbGe',
    url='https://gateway-lon.watsonplatform.net/natural-language-understanding/api'
)
l=[]
count=0
fh=open("C:\AIProject\dataset_label.txt","w")
fg=open("C:\AIProject\dataset_values.txt","w")
with open("C:\AIProject\dataset.txt") as f:
    for line in f:
        if count==20000:
            break
        elif re.match("^!!!!",line):
            try:
                s=" ".join(l)
                fin=pre_process(s)
                response = natural_language_understanding.analyze(
                text=fin,
                features=Features(categories=CategoriesOptions(limit=1))).get_result()
                fh.write(str(response["categories"][0]["label"])+"-"+str(response["categories"][0]["score"])+"\n")
                fg.write(fin+"\n\n")
                count=count+1
            except: 
                pass
            l=[]
        else: 
            l.append(line)
print(count)
fh.close()
fg.close()

In [ ]:
import numpy
import scipy
import re
import copy
import random
from sklearn.metrics import accuracy_score
import pickle
import json
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
import nltk
from nltk.corpus import stopwords
  
from keras.models import Sequential
from keras.layers import LSTM, Dense, Dropout, Masking, Embedding
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing import sequence
from keras.preprocessing.text import Tokenizer
from sklearn.model_selection import train_test_split

embedding_matrix={}
X=numpy.empty((20000,1),dtype=object)
label=numpy.empty((20000,6))
categories=["health and fitness","business and real estate","finance and politics","science and technology","sports and automotive","art, entertainment and society"]

def load():
  print("Loading X and label")
  global embedding_matrix,X,label,categories
  count=0
  with open("drive/My Drive/AIProject/dataset_values.txt","r") as f:
    l=[]
    for line in f:
      if count>=20000:
        break
      if re.match("^!!!!!",line):
        s=" ".join(l)
        text=s.split()
        for i in text:
          text[text.index(i)]=text[text.index(i)].strip()
        fin=[]
        for word in text:
          if word in embedding_matrix.keys():
            #print(word)
            fin.append(word)
        l=[]
        X[count][0]=str(" ".join(fin))
        count+=1
      else:
        l.append(line)
  count=0
  with open("drive/My Drive/AIProject/dataset_labels.txt","r") as f:
    vector=[]
    for i in range(6):
      vector.append(0)
    for line in f:
      if count>=20000:
        break
      h=line.strip()
      y=copy.deepcopy(vector)
      y[categories.index(h)]=1
      label[count]=y
      count+=1
  print(X.shape)
  print(label.shape)
  print("Done")    

def prepare_matrix():
    global embedding_matrix
    print("Preparing embedding matrix")
    fh=open("drive/My Drive/AIProject/embedding_matrix.pkl","rb")
    embedding_matrix=pickle.load(fh)
    fh.close()
    print(len(embedding_matrix.keys()))
    print("Done")
    
def prepare_for_model():
  print("Preparing for model")
  global X,label,embedding_matrix
  tokenizer = Tokenizer(num_words= 400000)
  tokenizer.fit_on_texts(numpy.asarray(list(embedding_matrix.keys())))
  fg=open("drive/My Drive/AIProject/embeddings.pkl","rb")
  embeddings=pickle.load(fg)
  fg.close()
  sequences = tokenizer.texts_to_sequences(X[:,0])
  data = pad_sequences(sequences,maxlen=30)
  print("Done")
  return data,embeddings





    
def train_using_API(data,embeddings):
  global label
  model = Sequential()
  model.add(Embedding(input_dim=400000,output_dim=300,weights=[embeddings],trainable=False,mask_zero=True))
  model.add(Masking(mask_value=0.0))
  model.add(LSTM(64, return_sequences=False, 
               dropout=0.1, recurrent_dropout=0.1))

  model.add(Dense(64, activation='tanh'))

  model.add(Dropout(0.5))

  model.add(Dense(6, activation='softmax'))

  model.compile(
    optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
  #x_train, x_test, y_train, y_test = train_test_split(data, label, test_size=0.25, shuffle= True)
  model.fit(data, label, batch_size=32, validation_split=0.25, epochs=100)
  #scores = model.evaluate(x_test, y_test)
  #print("Accuracy:", scores[1])  
  ff=open("drive/My Drive/AIProject/model_6.pkl","wb")
  pickle.dump(model,ff)
  ff.close()
      

prepare_matrix()
load()
d,e=prepare_for_model()
train_using_API(d,e)

Preparing embedding matrix
400000
Done
Loading X and label
(20000, 1)
(20000, 6)
Done
Preparing for model
Done
Train on 15000 samples, validate on 5000 samples
Epoch 1/100
15000/15000 [==============================] - 28s 2ms/step - loss: 1.7896 - acc: 0.2031 - val_loss: 1.7892 - val_acc: 0.1970
Epoch 2/100
15000/15000 [==============================] - 26s 2ms/step - loss: 1.7608 - acc: 0.2305 - val_loss: 1.7957 - val_acc: 0.1894
Epoch 3/100
15000/15000 [==============================] - 26s 2ms/step - loss: 1.7505 - acc: 0.2384 - val_loss: 1.7877 - val_acc: 0.2090
Epoch 4/100
15000/15000 [==============================] - 26s 2ms/step - loss: 1.7310 - acc: 0.2529 - val_loss: 1.8004 - val_acc: 0.2022
Epoch 5/100
15000/15000 [==============================] - 26s 2ms/step - loss: 1.7124 - acc: 0.2730 - val_loss: 1.8150 - val_acc: 0.1902
Epoch 6/100
15000/15000 [==============================] - 26s 2ms/step - loss: 1.6940 - acc: 0.2805 - val_loss: 1.8365 - val_acc: 0.1834
Epoch 7/100


KeyboardInterrupt: ignored

In [ ]:
print(label[:10])

[[0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]]


In [ ]:
import numpy
import scipy
import re
import copy
import random
from sklearn.metrics import accuracy_score
import pickle
import json
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
import nltk
from nltk.corpus import stopwords
  
from keras.models import Sequential
from keras.layers import LSTM, Dense, Dropout, Masking, Embedding
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing import sequence
from keras.preprocessing.text import Tokenizer
from sklearn.model_selection import train_test_split

embedding_matrix={}
X=numpy.empty((9993,1),dtype=object)
label=numpy.empty((9993,6))
categories=["business and industrial","science and technology","finance and news","education and government","fitness and automotive","art, entertainment and society"]

def load():
  print("Loading X and label")
  global embedding_matrix,X,label,categories
  count=0
  with open("drive/My Drive/AIProject/category.txt","r") as f:
    l=[]
    for line in f:
      if re.match("^/",line):
        s=" ".join(l)
        text=s.split()
        for i in text:
          text[text.index(i)]=text[text.index(i)].strip()
        fin=[]
        for word in text:
          if word in embedding_matrix.keys():
            #print(word)
            fin.append(word)
        l=[]
        X[count][0]=str(" ".join(fin))
        vector=[]
        for i in range(6):
          vector.append(0)
        h=line.split("/")
        if "-" in h[1]:
          j=h[1].split("-")
          h[1]=j[0]
        if h[1] in ("business and industrial"):
          cat="business and industrial"
        elif h[1] in ("technology and computing","science"):
          cat="science and technology"
        elif h[1] in ("finance","news","real estate"):
          cat="finance and news"
        elif h[1] in ("law, govt and politics","careers","education"):
          cat="education and government"
        elif h[1] in ("sports","automotive and vehicles","health and fitness"):
          cat="fitness and automotive"
        else:
          cat="art, entertainment and society"
        y=copy.deepcopy(vector)
        y[categories.index(cat)]=1
        label[count]=y
        count+=1
      else:
        l.append(line)
  print(X.shape)
  print(label.shape)
  print("Done")    

def prepare_matrix():
    global embedding_matrix
    print("Preparing embedding matrix")
    fh=open("drive/My Drive/AIProject/embedding_matrix.pkl","rb")
    embedding_matrix=pickle.load(fh)
    fh.close()
    print(len(embedding_matrix.keys()))
    print("Done")
    
def prepare_for_model():
  print("Preparing for model")
  global X,label,embedding_matrix
  tokenizer = Tokenizer(num_words= 400000)
  tokenizer.fit_on_texts(numpy.asarray(list(embedding_matrix.keys())))
  fg=open("drive/My Drive/AIProject/embeddings.pkl","rb")
  embeddings=pickle.load(fg)
  fg.close()
  sequences = tokenizer.texts_to_sequences(X[:,0])
  data = pad_sequences(sequences,maxlen=50)
  print("Done")
  return data,embeddings





    
def train(data,embeddings):
  global label
  model = Sequential()
  model.add(Embedding(input_dim=400000,output_dim=300,weights=[embeddings],trainable=False,mask_zero=True))
  model.add(Masking(mask_value=0.0))
  model.add(LSTM(64, return_sequences=False, 
               dropout=0.5, recurrent_dropout=0.5))

  #model.add(Dense(64, activation='relu'))

  model.add(Dropout(0.5))

  model.add(Dense(6, activation='softmax'))

  model.compile(
    optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
  #x_train, x_test, y_train, y_test = train_test_split(data, label, test_size=0.25, shuffle= True)
  model.fit(data, label, batch_size=32, validation_split=0.3, epochs=50)
  ff=open("drive/My Drive/AIProject/model_6.pkl","wb")
  pickle.dump(model,ff)
  ff.close()
      

prepare_matrix()
load()
d,e=prepare_for_model()
train(d,e)

Preparing embedding matrix
400000
Done
Loading X and label
(9993, 1)
(9993, 6)
Done
Preparing for model
Done
Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Use tf.cast instead.
Train on 6995 samples, validate on 2998 samples
Epoch 1/50
6995/6995 [==============================] - 21s 3ms/step - loss: 1.5608 - acc: 0.3751 - val_loss: 1.3772 - val_acc: 0.4206
Epoch 2/50
6995/6995 [==============================] - 19s 3ms/step - loss: 1.3520 - acc: 0.4905 - val_loss: 1.2804 - val_acc: 0.5137
Epoch 3/50
6995/6995 [==============================] - 19s 3ms/step - loss: 1.2603 - acc: 0.5337 - val_loss: 1.2228 - val_acc: 0.5440
Epoch 4/50
6995/6995 [==============================] - 19s 3ms/step - loss: 1.1917 - acc: 0.5675 - val_loss: 1.2143 - val_acc: 0.5600
Epoch 5/50
6995/6995 [==============================] - 19s 3ms/step

In [ ]:
global label
num=[]
for i in range(6):
  num.append(0)
for vec in label:
  for i in range(6):
    if vec[i]==1:
      x=i
      break
  num[x]+=1
print(num)

In [ ]:
import numpy
import re
import copy
import random
import pickle

from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
import nltk
from nltk.corpus import stopwords
  

from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing import sequence
from keras.preprocessing.text import Tokenizer
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')

categories=["business and industrial","science and technology","finance and news","education and government","fitness and automotive","art, entertainment and society"]

embedding_matrix={}
tag_dict={
    'J':wordnet.ADJ,
    'V':wordnet.VERB,
    "N": wordnet.NOUN,
    "R": wordnet.ADV
}
def get_pos_tag(word):
    tag=nltk.pos_tag([word])[0][1][0].upper()
    return tag_dict.get(tag,wordnet.NOUN)

def clean_text(text):
    
    text = text.lower().split()
    stops = set(stopwords.words("english"))
    text = [w for w in text if not w in stops and len(w) >= 3]   
    text = " ".join(text)    
    text = re.sub(r"[^a-z0-9']", " ", text)
    text = re.sub(r"what's", "what is ", text)
    text = re.sub(r"\'s", " 's ", text)
    text = re.sub(r"\'ve", " have ", text)
    text = re.sub(r"n't", " not ", text)
    text = re.sub(r"i'm", "i am ", text)
    text = re.sub(r"\'re", " are ", text)
    text = re.sub(r"\'d", " would ", text)
    text = re.sub(r"\'ll", " will ", text)
    text = re.sub(r"0"," zero ", text)
    text = re.sub(r"1"," one ", text)
    text = re.sub(r"2"," two ", text)
    text = re.sub(r"3"," three ", text)
    text = re.sub(r"4"," four ", text)
    text = re.sub(r"5"," five ", text)
    text = re.sub(r"6"," six ", text)
    text = re.sub(r"7"," seven ", text)
    text = re.sub(r"8"," eight ", text)
    text = re.sub(r"9"," nine ", text)
    text = re.sub(r"'", " ", text)
    text = re.sub(r"\s{2,}", " ", text)
    text = re.sub(r"\n","",text)

    sentence_clean=[]
    for word in text.split():
        sentence_clean.append(lemmatizer.lemmatize(word,get_pos_tag(word)))
    return " ".join(sentence_clean)

  
def prepare_for_model(text):
  global embedding_matrix
  print("Preparing for model")
  fh=open("drive/My Drive/AIProject/embeddings.pkl","rb")
  embeddings=pickle.load(fh)
  fh.close()
  ff=open("drive/My Drive/AIProject/embedding_matrix.pkl","rb")
  embedding_matrix=pickle.load(ff)
  ff.close()
  tokenizer = Tokenizer(num_words= 400000)
  tokenizer.fit_on_texts(numpy.asarray(list(embedding_matrix.keys())))
  sequences = tokenizer.texts_to_sequences([text])
  data = pad_sequences(sequences,maxlen=50)
  print("Done")
  return data,embeddings

def model(test,embeddings):
  global categories
  fg=open("drive/My Drive/AIProject/model_6.pkl","rb")
  model=pickle.load(fg)
  fg.close()
  out=model.predict(test)
  print("Output vector is: "+str(out))
  r=numpy.argmax(out)
  print("Category match: "+categories[r])
  

lemmatizer = WordNetLemmatizer() 
test="""Learning Takes You Everywhere. Explore knowledge and new skills with the best universities in the world. ... New Courses and Specializations Explore New Courses Learn high-impact career skills and earn a course certificate.Predictive ew! Python Data Products for Predictive Analytics UC San Diego Data products and predictive analytics are powering the AI revolution. Use Python and machine learning to start collecting, modeling, and deploying data-driven systems today.
Use Python to create interactive data visualizations and build demo systems
Transform real-world data for data-driven predictive tasks
Perform simple regressions and classifications using machine learning libraries
Discover predictive analytics and take your Python skills to the next level with this four-course Specialization from UC San Diego."""
test=clean_text(test)
d,e=prepare_for_model(test)
model(d,e)




[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
Preparing for model
Done
Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:
Use tf.cast instead.
Output vector is: [[1.7045073e-02 9.7869587e-01 2.3966162e-03 3.2284905e-04 4.0857447e-04
  1.1310281e-03]]
Category match: science and technology


In [ ]:
categories=["art and entertainment","automotive and vehicles","business and industrial","careers","education","family and parenting","finance","food and drink","health and fitness","hobbies and interests","home and garden","law, govt and politics","news","pets","real estate","religion and spirituality","science","shopping","society","sports","style and fashion","technology and computing","travel"]

fh=open("drive/My Drive/AIProject/dataset_labels.txt","w")
with open("drive/My Drive/AIProject/dataset_label.txt","r") as f:
  for line in f:
    cat=""
    h=line.split("/")
    if "-" in h[1]:
      j=h[1].split("-")
      h[1]=j[0]
    if h[1] in ("health and fitness"):
      cat="health and fitness"
    elif h[1] in ("business and industrial","real estate"):
      cat="business and real estate"
    elif h[1] in ("finance","news","careers","law, govt and politics"):
      cat="finance and politics"
    elif h[1] in ("technology and computing","science","education"):
      cat="science and technology"
    elif h[1] in ("sports","automotive and vehicles"):
      cat="sports and automotive"
    else:
      cat="art, entertainment and society"
    fh.write(str(cat)+"\n")
    
fh.close()
   
    

In [ ]:
import numpy
a=numpy.array([[1],[2],[3],[4],[5],[6]])
r=numpy.argmax(a)
print(r)
#print(r[0][0])

5


In [ ]:
"import numpy
import scipy
import re
import copy
import random
from sklearn.metrics import accuracy_score
  
from keras.models import Sequential
from keras.layers import LSTM, Dense, Dropout, Masking, Embedding
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing import sequence
from keras.preprocessing.text import Tokenizer

def prepare_for_model():
  global X,label,embedding_matrix
  tokenizer = Tokenizer(num_words= 400000)
  tokenizer.fit_on_texts(numpy.asarray(list(embedding_matrix.keys())))
  embeddings = numpy.zeros((400000, 300))
  for word,number in tokenizer.word_index.items():
    embedding_vector = embedding_matrix.get(word)
    if embedding_vector is not None:
        embeddings[number]=embedding_vector
  sequences = tokenizer.texts_to_sequences(X[:,0])
  data = pad_sequences(sequences)
  return data,embeddings

def prepare_matrix():
    global embedding_matrix
    print("Preparing embedding matrix")
    with open("drive/My Drive/AIProject/glove.6B.300d.txt","r") as f:
        for line in f:
            row=line.split()
            word=row[0]
            del row[0]
            for i in range(300):
                row[i]=float(row[i])
            embedding_matrix[word]=list(row)
    print(len(embedding_matrix.keys()))
    print("Done")

  
d,e=prepare_for_model()
prepare_matrix()


In [ ]:
import numpy
import scipy
import re
import copy
import random
from sklearn.metrics import accuracy_score
  
from keras.models import Sequential
from keras.layers import LSTM, Dense, Dropout, Masking, Embedding

embedding_matrix={}
X=[]
label=[]
categories=["art and entertainment","automotive and vehicles","business and industrial","careers","education","family and parenting","finance","food and drink","health and fitness","hobbies and interests","home and garden","law, govt and politics","news","pets","real estate","religion and spirituality","science","shopping","society","sports","style and fashion","technology and computing","travel"]

def load():
  print("Loading X and label")
  global embedding_matrix,X,label,categories
  with open("drive/My Drive/AIProject/dataset_values.txt","r") as f:
    l=[]
    for line in f:
      if re.match("^!!!!!",line):
        s=" ".join(l)
        text=s.split()
        for i in text:
          text[text.index(i)]=text[text.index(i)].strip()
        fin=[]
        for word in text:
          if word in embedding_matrix.keys():
            #print(word)
            fin.append(word)
        l=[]
        X.append(fin)
      else:
        l.append(line)
  with open("drive/My Drive/AIProject/dataset_label.txt","r") as f:
    vector=[]
    for i in range(23):
      vector.append(0)
    for line in f:
      h=line.split("/")
      if "-" in h[1]:
        j=h[1].split("-")
        h[1]=j[0]
      y=copy.deepcopy(vector)
      y[categories.index(h[1])]=1
      label.append(y)
  print("Done")    

def prepare_matrix():
    global embedding_matrix
    print("Preparing embedding matrix")
    with open("drive/My Drive/AIProject/glove.6B.300d.txt","r") as f:
        for line in f:
            row=line.split()
            word=row[0]
            del row[0]
            for i in range(300):
                row[i]=float(row[i])
            embedding_matrix[word]=list(row)
    print(len(embedding_matrix.keys()))
    print("Done")
"""    
def pre_process(email):
    stopwords = ["a", "share", "linkthese", "about", "above", "after", "again", "against", "all", "am", "an", "and", "any","", "are","aren't","as","at","be","because","been","before","being","below","between","both","but","by","can't","cannot","could","couldn't","did","didn't","do","does","doesn't","doing","don't","down","during","each","few","for","from","further","had","hadn't","has","hasn't","have","haven't","having","he","he'd","he'll","he's","her","here","here's","hers","herself","him","himself","his","how","how's","i","i'd","i'll","i'm","i've","if","in","into","is","isn't","it","it's","its","itself","let's","me","more","most","mustn't","my","myself","no","nor","not","of","off","on","once","only","or","other","ought","our","ours","ourselves","out","over","own","same","shan't","she","she'd","she'll","she's","should","shouldn't","so","some","such","than","that","that's","the","their","theirs","them","themselves","then","there","there's","these","they","they'd","they'll","they're","they've","this","those","through","to","too","under","until","up","very","was","wasn't","we","we'd","we'll","we're","we've","were","weren't","what","what's","when","when's","where","where's","which","while","who","who's","whom","why","why's","with","won't","would","wouldn't","you","you'd","you'll","you're","you've","your","yours","yourself","yourselves", "this"];
    text=list(email)
    #print(text)
    for i in text:
        if i in (',','.','?'):
            del text[text.index(i)]
    email1="".join(text)
    text=email1.split(" ")
    final=[]
    for word in text:
        text[text.index(word)]=word.lower()
    for word in text:
        if word not in stopwords:
            final.append(word)
    return final
"""
    
def sigmoidGrad(z):
    r=z.shape[0]
    c=z.shape[1]
    res=numpy.zeros((r,c))
    for i in range(r):
        for j in range(c):
            res[i][j]=z[i][j]*(1-z[i][j])
    return res
        
"""   
def forw_back_prop(n,email_vector,y):
    global W,theta,loss,delta1,delta2
"""
def sigmoid(z):
    r=z.shape[0]
    c=z.shape[1]
    y=numpy.zeros((r,c))
    for i in range(r):
        for j in range(c):
            y[i][j]=1.0/(1.0+numpy.exp(-z[i][j]))
    return y

def comp_cost(nn_params):
    global embedding_matrix,X,label,train_count
    train_count=0
    loss=0
    W=numpy.zeros((1,301))
    theta=numpy.zeros((23,1))
    for i in range(301):
        W[0][i]=nn_params[i]
    for j in range(23):
        theta[j][0]=nn_params[301+j]
    for i in range(0,15000):
        email_text=X[i]
        #print(email_text)
        if len(email_text)<2:
          continue
        train_count+=1
        y=numpy.zeros((23,1))
        for k in range(23):
          y[k][0]=label[i][k]
        a=numpy.zeros((len(email_text)+1,1,1))
        a[0]=0
        for i in range(1,len(email_text)+1):
            ax=numpy.zeros((301,1))
            ax[0]=a[i-1]
            word_embed=embedding_matrix[email_text[i-1]]
            for j in range(300):
                ax[1+j][0]=word_embed[j]
            a[i]=numpy.tanh(numpy.dot(W,ax))
        output=sigmoid(numpy.dot(theta,a[len(email_text)]))
        c=[]
        csum=0
        for i in range(23):
            c.append((y[i]*numpy.log(output[i][0]))+((1-y[i])*numpy.log(1-output[i][0])))
            csum=csum+c[i]
        loss=loss+csum
    print(train_count)
    J=(-1/train_count)*loss
    return J

def comp_gradient(nn_params):
    global embedding_matrix,X,label
    train_count=0
    delta3=numpy.zeros((23,1))
    delta2=numpy.zeros((1,1))
    delta1=numpy.zeros((1,1))
    W=numpy.zeros((1,301))
    theta=numpy.zeros((23,1))
    for i in range(301):
        W[0][i]=nn_params[i]
    for j in range(23):
        theta[j][0]=nn_params[301+j]
    for i in range(0,15000):
        email_text=X[i]
        if len(email_text)<2:
          continue
        train_count+=1
        y=numpy.zeros((23,1))
        for k in range(23):
          y[k][0]=label[i][k]
        a=numpy.zeros((len(email_text)+1,1,1))
        a[0]=0
        for i in range(1,len(email_text)+1):
            ax=numpy.zeros((301,1))
            ax[0]=a[i-1]
            word_embed=embedding_matrix[email_text[i-1]]
            for j in range(300):
                ax[1+j][0]=word_embed[j]
            a[i]=numpy.tanh(numpy.dot(W,ax))
        output=sigmoid(numpy.dot(theta,a[len(email_text)]))
        del4=numpy.subtract(y,output)
        del3=numpy.dot((numpy.dot(numpy.transpose(theta),del4)),(sigmoidGrad(a[len(email_text)])))
        del2=numpy.dot((numpy.dot(numpy.transpose(W),del3)),(1-(numpy.tanh(a[len(email_text)-1]))**2))
        delta1=numpy.add(delta1,numpy.dot(del2,numpy.transpose(a[len(email_text)-2])))
        delta2=numpy.add(delta2,numpy.dot(del3,numpy.transpose(a[len(email_text)-1])))
        delta3=numpy.add(delta3,numpy.dot(del4,numpy.transpose(a[len(email_text)])))
    grad=[]
    grad.append(delta1[0][0])
    grad.append(delta2[0][0])
    for i in range(23):
        grad.append(delta3[i][0])
    grad=numpy.ravel(grad)
    return grad

def train():
    global X,label
    print("Training")
    W=numpy.zeros((1,301))
    for i in range(301):
      W[0][i]=random.random()
    theta=numpy.zeros((23,1))
    for i in range(23):
      theta[i][0]=random.random()
    #Load email vectors to X and labels to label
    para=[]
    for i in range(301):
        para.append(W[0][i])
    for i in range(23):
        para.append(theta[i][0])
    initial_nn_params=numpy.ravel(para)
    #costFunction=comp_cost(nn_params,X,label)
    #nn_grad=comp_gradient(nn_params,X,label)
    final_nn_params=scipy.optimize.fmin_cg(comp_cost,x0=initial_nn_params,maxiter=50)
    print(final_nn_params.shape)
    for i in range(301):
        W[0][i]=final_nn_params[i]
    for j in range(23):
        theta[j][0]=final_nn_params[301+j]
    return W,theta
    print("Done")
    
def train_using_API():
  global X,label,embedding_matrix
  model = Sequential()
  model.add(Embedding(input_dim=1000,output_dim=300,weights=[embedding_matrix],trainable=False,mask_zero=True))
  model.add(Masking(mask_value=0.0))
  model.add(LSTM(64, return_sequences=False, 
               dropout=0.1, recurrent_dropout=0.1))

  model.add(Dense(64, activation='relu'))

  model.add(Dropout(0.5))

  model.add(Dense(num_words, activation='softmax'))

  model.compile(
    optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
  model.fit(X[:15000], label[:15000], batch_size=2048, epochs=10)
  scores = model.evaluate(X[15000:], label[15000:])
  print("Accuracy:", scores[1])  
    
def test_avg(W,theta):
  print("Testing")
  global embedding_matrix,X,label
  err_sum=0
  for i in range(15000,20000):
    email_text=X[i]
    y=numpy.zeros((23,1))
    for k in range(23):
      y[k][0]=label[i][k]
    a=numpy.zeros((len(email_text)+1,1,1))
    a[0]=0
    for i in range(1,len(email_text)+1):
      ax=numpy.zeros((301,1))
      ax[0]=a[i-1]
      word_embed=embedding_matrix[email_text[i-1]]
      for j in range(300):
        ax[1+j][0]=word_embed[j]
      a[i]=numpy.tanh(numpy.dot(W,ax))
    output=sigmoid(numpy.dot(theta,a[len(email_text)]))
    err=0
    for i in range(23):
      err+=(y[i]-output[i])
    err_sum+=(err/23.0)
  return (1-(err_sum/5000))
  print("Done")
  
def test_classifier(W,theta):
  print("Testing")
  global embedding_matrix,X,label
  y_pred=[]
  y_actual=[]
  err_sum=0
  for i in range(15000,20000):
    email_text=X[i]
    y_actual.append(label[i].index(1))
    a=numpy.zeros((len(email_text)+1,1,1))
    a[0]=0
    for i in range(1,len(email_text)+1):
      ax=numpy.zeros((301,1))
      ax[0]=a[i-1]
      word_embed=embedding_matrix[email_text[i-1]]
      for j in range(300):
        ax[1+j][0]=word_embed[j]
      a[i]=numpy.tanh(numpy.dot(W,ax))
    output=sigmoid(numpy.dot(theta,a[len(email_text)]))
    y_pred.append(output.index(max(output)))
  return sklearn.metrics.accuracy_score(y_actual,y_pred)
  print("Done")
  
prepare_matrix()
load()
#W_fin,theta_fin=train()
#print("Accuracy (average) of model is "+str(test_avg(W_fin,theta_fin)))
#print("Accuracy (correct classification) is "+str(test_classifier(W_fin,theta_fin)))
train_using_API